name: outtheresocialclub
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  mysql1: ^0.20.0
  flutter_secure_storage: ^9.0.0
  url_launcher: ^6.1.7
  cupertino_icons: ^1.0.6
  jwt_decoder: ^2.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - lib/assets/logos/OTSC_Logo_Horizontal_FullColor.png
    - lib/assets/logos/OTSC_Logo_Wordmark_Horizontal_Black.png
  uses-material-design: true